Develop
amklass11/js-capstone pull request #1
Opened 2022-06-04 04:28 UTC by amklass11

1. home page built
2. comments section built
3. test integrated

2022-06-04 04:52 UTC, Ismailco reviewed
Hi @amklass11,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has no professional documentation, video presentation, or uses peer programming, please modify your README (you can use [this template](https://github.com/microverseinc/readme-template)) to be more professional and add a video with your partner describing the project. also, you should give and receive code reviews from your partner in separate Pull Requests to the project, [check this link](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/code_review_flow_group_projects.md) for more details.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-06-04 07:34 UTC, descholar-ceo requested changes
Hi @amklass11, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-04 07:34 UTC, descholar-ceo commented on README.md
> +This  project is aimed at building a beautiful porfolio page.
- [ ] This readme file contains inappropriate or not clear project description hence this will make your project to look unprofessional

2022-06-04 07:34 UTC, descholar-ceo commented on README.md
> +
- [ ] This live demo link does not work at all
![Screenshot from 2022-06-04 09-25-25](https://user-images.githubusercontent.com/56886064/171989356-728b1f2d-56d5-46e7-823c-7feec3eb7005.png)

2022-06-04 07:34 UTC, descholar-ceo commented on README.md
> +This project is [MIT](./MIT.md) licensed.
- [ ] [OPTIONAL] Kindly make sure that all of the links presented on readme file work as expected, and that will make your project way professional, so fix this license link
![Screenshot from 2022-06-04 09-27-17](https://user-images.githubusercontent.com/56886064/171989419-1397a03b-58b7-4701-b990-4886fc4493f3.png)

2022-06-04 07:34 UTC, descholar-ceo commented on README.md
> +[MOVIES demo](https://youtu.be/PdEa4KJuPNk)
- [ ] The video contains a clear and objective description of the project in professional English. The topic and purpose of the project are made clear.
- [ ] The video contains a highlight about a piece of the code the student finds interesting or is proud of making.
- [ ] Try to record a new video with more clear sounds

2022-06-04 07:34 UTC, descholar-ceo commented on README.md
> + css and js by building the Movie app of the website.
- [ ] The getting started section of the readme file should describe how we setup and run the project on local environment, kindly put the description at the top in description section

2022-06-05 01:17 UTC, bimbolabuari approved these changes
Hi @amklass11

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-05 01:18 UTC, merged

2022-06-05 01:21 UTC, amklass11 commented
@bimbolabuari  Hello  thanks but I can't submit on dashboard review still pending